= Internet-Draft: SM3

image:https://img.shields.io/travis/riboseinc/rfc-crypto-sm3/master.svg[
	Build Status, link="https://travis-ci.org/riboseinc/rfc-crypto-sm3"]

This Internet-Draft is written in AsciiRFC using the excellent
https://github.com/riboseinc/asciidoctor-rfc[`asciidoctor-rfc` gem].

== Fetching the document

[source,sh]
----
git clone https://github.com/riboseinc/rfc-crypto-sm3
----

== Installing Build Tools

You will need Ruby, `xml2rfc` and `idnits` (for submission preflight).

=== On macOS

[source,sh]
----
brew install idnits
brew install python
easy_install pip
pip install -r requirements.txt
gem install bundler
bundle install
----

== Building The Document

[source,sh]
----
make all
# or
export ID_NAME=ribose-cfrg-sm3
make draft-${ID_NAME}.txt
----

== Checking Against idnits

https://tools.ietf.org/tools/idnits/[idnits] is the RFC checking tool prior to
submissions.

The `make` target finds exactly the document name from the `:name:` document
attribute and puts the file in the right place before calling `idnits` to
prevent it complaining about the location.

[source,sh]
----
export ID_NAME=ribose-cfrg-sm3
make draft-${ID_NAME}.nits
----

== Checking for invalid / unicode characters

[source,sh]
----
export ID_NAME=ribose-cfrg-sm3
pcregrep --color='auto' -n "[\x80-\xFF]" draft-${ID_NAME}.xml
----

== Iterating the document

[source,sh]
----
export ID_NAME=ribose-cfrg-sm3
make clean all; open draft-${ID_NAME}.txt
----

== Generating Examples From Code

[source,sh]
----
cd code
make clean sm3_test
./sm3_test
----

If you want to see the inner states, enable `#define DEBUG 1` in
`code/print.h`, which will give you the exact output seen in
the examples section with message extension, compression, etc.

Which is quite awesome.

