
= Introduction

SM3 <<GBT.32905-2016>> <<ISO.IEC.10118-3>> is a cryptographic hash algorithm
published by the Organization of State Commercial Administration of China <<OSCCA>>
as an authorized cryptographic hash algorithm for the use within China.
The algorithm is published in public.

The SM3 algorithm is intended to address multiple use cases for commercial
cryptography, including, but not limited to:

* the use of digital signatures and their verification;
* the generation and verification of message authenticity codes; as well as
* the generation of random numbers.

SM3 has a Merkle-Damgard construction and is similar to SHA-2
<<NIST.FIPS.180-4>> of the MD4 <<RFC6150>> family, with the addition of several
strengthening features including a more complex step function and stronger
message dependency than SHA-256 <<SM3-Details>>.

SM3 produces an output hash value of 256 bits long, based on 512-bit
input message blocks, on input lengths up to $$2^(m)$$ <<GBT.32905-2016>>.

This document details the SM3 algorithm and its internal steps together
with demonstrative examples.


== Purpose

This document does not aim to introduce a new algorithm, but to
provide a clear and open description of the SM3 algorithm in English,
and also to serve as a stable reference for IETF documents that utilize
this algorithm.

This document follows the updated description and structure of <<GBT.32905-2016>>
published in 2016.

Sections 1 to 5 of this document directly map to the corresponding sections
(and numbering) of the <<GBT.32905-2016>> standard for
convenience of the reader.

Sections 6 to 8 of this document provides a translation of the design
considerations, hardware adaptability, and cryptanalysis results of
SM3 in the words of its designer, Xiaoyun Wang, given in <<SM3-Details>>.


== History

The SM4 algorithm was designed by Xiaoyun Wang <<WXY>> et al.

It was first published by the OSCCA <<OSCCA>> in public in 2010 <<OSCCA-SM3>>,
then published as a China industry standard in 2012 <<GMT-0004-2012>>, and
finally published as a Chinese National Standard (GB Standard)
<<GBT.32905-2016>> in 2016. SM3 has been standardized in <<ISO.IEC.10118-3>> by
the International Organization for Standardization in 2017.

The latest SM3 standard <<GBT.32905-2016>> was proposed by the OSCCA,
standardized through TC 260 of the Standardization Administration of the
People's Republic of China (SAC), and was drafted by the following
individuals at Tsinghua University,
the China Commercial Cryptography Testing Center,
the People's Liberation Army Information Engineering University,
and the Data Assurance and Communication Security Research
Center (DAS Center) of the Chinese Academy of Sciences:

* Xiao-Yun Wang
* Zheng Li
* Yong-Chuan Wang
* Hong-Bo Yu
* Yong-Quan Xie
* Chao Zhang
* Peng Luo
* Shu-Wang Lu


== Applications

//# TODO

SM3 has prevalent hardware implementations, due to its being the only OSCCA-approved cryptographic hash
algorithm allowed for use in China <<SM3-Details>>.

