
= Introduction

SM3 [@!GBT.32905-2016] [@ISO.IEC.10118-2] is a cryptographic hash algorithm
published by the Organization of State Commercial Administration of China [@OSCCA]
as an authorized cryptographic hash algorithm for the use within China.
The algorithm is published in public.

The SM3 algorithm is intended to address multiple use cases for commercial
cryptography, including the use of digital signatures and their verification,
the generation and verification of message authenticity codes, as well as the
generation of random numbers.

This document details the SM3 algorithm and its internal steps together
with demonstrative examples.

== Purpose

This document does not aim to introduce a new algorithm, but to
provide a clear and open description of the SM3 algorithm in English,
and also to serve as a stable reference for IETF documents that utilize
this algorithm.

This document follows the updated description and structure of [@!GBT.32905-2016]
published in 2016. Sections 1 to 5 of this document directly map to the
corresponding sections numbers of the [@!GBT.32905-2016] standard for
convenience of the reader.

This document also provides additional information on the practical usage and
implementation of SM3, specifying multiple modes of operations that are known
to be used with SM3 and providing the SM3 OIDs.


== History

The SM4 algorithm was invented by Xiao-Yun Wang [@WXY], first published as a
public document by the OSCCA [@OSCCA] in 2010, then standardized as
[@GMT-0004-2012] also published by the OSCCA,
and finally confirmed in 2016 as a Chinese National Standard (GB Standard)
[@!GBT.32905-2016]. SM3 is also standardized in [@ISO.IEC.10118-3]
by the International Organization for Standardization in 2017.

The latest SM3 standard [@!GBT.32905-2016] was proposed by the OSCCA,
standardized through TC 260 of the Standardization Administration of the
People's Republic of China (SAC), and was drafted by the following
individuals at Tsinghua University,
the China Commercial Cryptography Testing Center,
the People's Liberation Army Information Engineering University,
and the Data Assurance and Communication Security Research
Center (DAS Center) of the Chinese Academy of Sciences:

* Xiao-Yun Wang
* Zheng Li
* Yong-Chuan Wang
* Hong-Bo Yu
* Yong-Quan Xie
* Chao Zhang
* Peng Luo
* Shu-Wang Lu


== Applications

TODO

SM3 has prevalent hardware implementations, due to its being the only OSCCA-approved cryptographic hash
algorithm allowed for use in China.


== Cryptanalysis

A number of attacks have been attempted on SM3, such as
...

TODO

