= Cryptanalysis

//本节给出了 SM3密码杂凑算法的安全性分析结果.同时将SM3密码杂凑算法和ISO/IEC 10118-3标准算法以及部分国家标准杂凑算法根 据已有的公开分析结果在安全性上进行比较.

////
== 4.1 SM3密码杂凑算法的安全性分析结果

目前已公开发表的针对SM3密码杂凑算法 的安全性分析的论文集中在碰撞攻击、原像攻击 和区分攻击3个方面.


模差分分析方法[3"5]是寻找杂凑算法碰撞最 常用的方法，一般分析过程可以推述如下:1)选择 合适的消息差分，它决定了攻击成功的概率;2)针 对选择的消息差分寻找可行的差分路线;3)推导 出保证差分路线可行的充分条件，在寻找差分路 线的过程中，链接变量的条件被确定下来，一个可 行的差分路线就意味着从路线上推导出来的所有 的链接变量的条件相互之间没有冲突J)使用消
IfVl IWW 	 IW\
使用中间相遇攻击方法，Zou等人[24]在 ICISC 2011上给出了从第1步开始的28步SM3 密码杂凑算法的原像攻击和从中间开始的30步 SM3密码杂凑算法的原像攻击.2012年，Wang和 ShenE®使用差分中间相遇攻击方法给出了 29步 和30步SM3密码杂凑算法的原像攻击，同时给 出了 31步和32步SM3密码杂凑算法的伪原像攻 击.所有的分析结果均从第1步开始.
对SM3密码杂凑算法的区分攻击主要是使 用飞去来器(boomerang)区分攻击，其主要思想是
息修改技术，使得被修改的消息满足尽可能多的 充分条件.近年又出现了使用自动化搜索方法寻 找差分路线[1W7].针对SM3密码杂凑算法的特 性，Mendel等人[如在CT-RSA 2013上给出了 20 步可实现复杂度的SM3密码杂凑算法的碰撞攻 击和24步可实现复杂度的自由起始碰撞攻击.
Merkle~Damg4rd结构杂凑算法的原像攻击 主要采用中间相遇攻击[1^]及其改进方法，比如 差分中间相遇攻击[21]等.寻找原像的过程首先需 要寻找单个消息分组的伪原像，之后使用伪原像 转化原像的方法[22]将伪原像转化为多个分组的原 像寻找伪原像的过程可以描述如下:1)选择合适 的独立消息字(或比特），记为独立消息字I和独 立消息字n.并根据独立消息字将压缩函数分成3 个部分，分别记为独立部分I、独立部分n和匹配 部分.其中，独立消息字I和独立部分n，独立消 息字n和独立部分I相互独立.2)随机设定除独 立消息字I和n之外的其他消息和独立部分I和 n位置的链接变量.3)利用独立消息字I和独立 部分I计算列表“，利用独立消息字n和独立部 分n计算列表l2. 4)寻找^和l2的一个碰撞， 此碰撞对应的初始值和消息即为一个伪原像.随 后又出现了带完全二分结构体[23]的中间相遇攻击 等方法.带完全二分结构体的中间相遇攻击如图3 所示，其中jw In表示独立消息字.
IWW 匹配部分 JW1
I	I	1	,
IYI
独立部分II | |独立部分I
使用中间一步或者多步链接变量的衔接将2条短 的差分路线构造长的差分路线，进而构造出满足输 入输出差分的四元组.如图4所示，一般过程可以 描述如下:1)选择合适的消息差分，构造攻击所需 的短差分路线.消息差分的选取应尽量是充分条 件出现在衔接位置附近.2)检测衔接位置的充分 条件是否矛盾.3)随机选择衔接位置的链接变量， 使用消息修改技术，使得被修改的消息满足尽可能 多的充分条件.4)从衔接位置开始，向两端构造相 应测差分路线，进而推导出对应的输入输出差分. 


在 SAC 2012 上，Kircanski 等人[26]给出了 32 步到35步SM3密码杂凑算法压缩函数的飞去来 器区分攻击，同时给出了 32步和33步的区分攻 击实例以及利用SM3密码杂凑算法的移位特点， 给出了 SM3-XOR(将SM3密码杂凑算法中所有 的非线性运算用异或运算代替)的滑动-移位特性. 2014年，Bai等人[27]改进了 SM3密码杂凑算法的 飞去来器区分攻击，给出了 34步到37步飞去来 器区分攻击以及34步和35步的区分攻击实例. SM3密码杂凑算法的分析结果如表4所示：

SM3密码杂凑算法和其他杂凑标准SHA-1， SHA-2, RIPEMD-128, RIPEMD-160, Whirlpool, Stribog和KECCAK的安全性分析对比结果如 表5所示：
从表5可以得出:在碰撞攻击方面，SM3密码 杂凑算法的攻击百分比仅比KECCAK高，比其他 杂凑标准低，但在MI>SHA类算法中最低，仅占 总步数的31%;在原像攻击方面，SM3密码杂凑 算法的攻击百分比仅比KECCAK高，比其他杂凑 标准低，但在MI>SHA类算法中最低，占总步数 的47%;在区分器攻击方面，SM3密码杂凑算法 均比其他杂凑标准低，仅有58%，约占总步数的一 半左右.这些分析结果体现了 SM3密码杂凑算法 的高安全性.

////

