= Hardware Realization

////
== 3	SM3密码杂凑算法的软硬件实现
SM3密码杂凑算法结构上和SHA-256相似，并且链接变量长度、消息分组大小和步数均与 SHA-256相同.测试向量和C程序代码见附录A 和附录B.本节从32 b平台软件性能、ASIC芯片实现性能和FPGA平台实现性能3个方面将SM3 密码杂凑算法和 SHA-256, SHA-512, Whirlpool 与SHA-3进行比较.
////

////
== 3.1 软件实现及性能

SM3密码杂凑算法和SHA-256，SHA-512, Whirlpool与SHA-3软件实现及性能测试环境 如下.
1)	处理器:Intel㊣ Core™ i7-4770 @ 3. 4GHz;
2)	内存:8 GB;
3)	操作系统:64 b Windows 7操作系统；
4)	编译环境^Visual Studio 2010.
其中，SHA-256，SHA-512，Whirlpool 与 SHA-3 为OpenSSL实现.测试分别在Win32平台和X64 平台下，对各种算法在输入长度分别为16 B，64 B， 1024 B和8192 B的情况下进行，详细结果如表1 所示：
表1 SM3密码杂凑算法和其他标准软件速度cycles/B
平台	算法		输入长度
		16B	64 B	1024B	8192B
	SM3	83	40	21	19
	SHA-256	104	44	20	16
Win32	SHA-512	517	131	39	32
	Whirlpool	245	126	71	68
	SHA3-256	450	109	53	50
	SM3	63	30	16	15
	SHA-256	76	34	16	14
X64	SHA-512	149	43	12	9
	Whirlpool	113	60	37	36
	SHA3-256	95	23	10	10
从表1可以得出:在Win32和X64环境下，当 消息长度为16 B时，SM3密码杂凑算法的软件执行速度高于其他4种算法，速度为SHA-256的 125%;在Win32环境下，当消息长度大于等于64 B 时，SM3密码杂凑算法的软件执行速度和SHA-256相当，高于其他3种算法;在X64环境下，当消息长 度等于64 B时，SM3密码杂凑算法的软件执行速度 和 SHA-256 相当，低于 SHA3-256,髙于 SHA-512 和Whirlpool;在X64环境下，当消息长度大于64B 时，SM3密码杂凑算法的软件执行速度和SHA-256 相当，低于 SHA-512 和 SHA3-256,高于 Whirlpool.


== 3.2 ASIC芯片实现及性能
SM3密码杂凑算法和SHA-256、SHA-512、 Whirlpool 与 SHA-3 在 COMS 0• 18 pm 工艺下的 ASIC芯片实现及性能如表2所示：
表2 SM3密码杂凑算法和其他标准的ASIC实现
算法	面积
(gates)	时钟
/MHz	吞吐量
/Mbps	吞吐量面积比 /(Kbps/gate)
SM3[10]	11068	216. 00	1619	146. 28
SHA-256[n]	15 400	189. 75	1349	87. 60
SHA-512tn]	30 747	169. 20	1969	64. 04
Whirlpool^11]	38911	101. 94	2 485	63.86
SHA-3[12]	56 320	487. 80	21229	376. 94
从表2可以得出:SM3密码杂凑算法的ASIC 实现面积要优于其他4种算法，实现面积分别为 其他算法的72%，36%，28%和20%，吞吐量介于 SHA-256和SHA-512之间，吞吐量面积比仅低于 SHA-3,优于其他3种算法.整体而言，SM3密码 杂凑算法为性能优越的Merkle-DamgArd结构杂凑算法.
3*3 FPGA平台上的实现及性能
SM3密码杂凑算法和SHA-256的FPGA实现 平台为Xilinx Virtex-5，其实现及性能如表3所示：
////