
[#cryptanalysis]
= Cryptanalysis

TODO: This section is WIP.

////
本节给出了SM3密码杂凑算法的安全性分析结果.同时将SM3密码杂凑算法和
ISO/IEC 10118-3标准算法以及部分国家标准杂凑算法根 据已有的公开分析
结果在安全性上进行比较.
////

This section provides the latest cryptanalysis results of the SM3 algorithm,
and compares it with cryptanalysis of algorithms specified in
<<ISO.IEC.10118-3>> as well as other standard hash algorithms.

== Analysis

////
== 4.1 SM3密码杂凑算法的安全性分析结果

目前已公开发表的针对SM3密码杂凑算法的安全性分析的论文集中在碰撞攻击、
原像攻击和区分攻击3个方面.
////

Current published cryptanalysis research mainly focuses on collision attacks,
preimage attacks and distinguishing attacks.

////
== Differential Analysis
模差分分析方法[3-5]是寻找杂凑算法碰撞最常用的方法，一般分析过程可以推述如下:
1)选择合适的消息差分，它决定了攻击成功的概率;
2)针对选择的消息差分寻找可行的差分路线;
3)推导出保证差分路线可行的充分条件，在寻找差分路线的过程中，
链接变量的条件被确定下来，一个可行的差分路线就意味着从路线上推导出来的
所有的链接变量的条件相互之间没有冲突
4)使用消息修改技术，使得被修改的消息满足尽可能多的充分条件.近年又出现了
使用自动化搜索方法寻找差分路线[16-17].针对SM3密码杂凑算法的特性，
Mendel等人[18]如在CT-RSA 2013上给出了20步可实现复杂度的SM3密码杂凑算法的
碰撞攻击和24步可实现复杂度的自由起始碰撞攻击.

部分术语（取自王教授部分论文）：
模差分分析：modular differential crypanalysis
差分路线：diferential path
链接变量：chaining variable
消息修改技术：message modification technology
////

=== Collision Attack

The modular differential cryptanalysis is the most common way to find
collisions of hash algorithms. It is generally described as following steps:

1. Select a proper input difference, which decides the probablity of a
successful attack.

2. Search for a feasible differential path for the selected input difference.

3. Export the sufficient conditions that guanrantee the feasibility of the
differential path. During the search of the differential path, if conditions
of chaining variables are fixed, a feasible differential path means all conditions
of chaining variables that are derived from the path have no conflicts with
each other.

4. Apply message modification technology to fulfill as many sufficient conditions
as possible.

Recent years several automated searching methods for differential paths have
been published. Based on characteristics of the SM3 algorithm, Mendel et al. presented
a 20-step collision attack and a 24-step freestart collision attack against
SM3 at CT-RSA 2013.

////
Merkle-Damgard结构杂凑算法的原像攻击主要采用中间相遇攻击[19-20]
及其改进方法，比如差分中间相遇攻击[21]等. 
寻找原像的过程首先需要寻找单个消息分组的伪原像，之后使用
伪原像转化原像的方法[22]将伪原像转化为多个分组的原像寻找
伪原像的过程可以描述如下:

1)选择合适的独立消息字(或比特），记为独立消息字I和独立消息字II.并根据独
立消息字将压缩函数分成3个部分，分别记为独立部分I、独立部分II和匹配部分.
其中，独立消息字I和独立部分II，独立消息字II和独立部分I相互独立.
2)随机设定除独立消息字I和II之外的其他消息和独立部分I和II位置的链接变量.
3)利用独立消息字I和独立部分I计算列表L_1，利用独立消息字II和独立部分II计
算列表L_2.
4)寻找L_1和L_2的一个碰撞，此碰撞对应的初始值和消息即为一个伪原像.
////

=== Preimage Attack

The preimage attack against Merkle-Damgard construction hash algorithm mainly
uses meet-in-the-middle attack and its improved variants like differential
meet-in-the-middle attack etc as the method. While searching for preimages,
the pseudo preimage of single message block needs to be found first and then
the pseudo preimage is converted to preimage of multiple blocks.

The steps of searching for pseudo preimage can be described as follows:

1. Select a proper independent message word (or bit), note as independent
message word I and independent message word II and split the compression
function into three parts, the independent part I, the independent part II and
the match part base on the independent message. The independent message word I
and the independent part II are independent from each other, as well as the
independent message word II and the independent part I.

2. Randomly set other messages other than the independent message word I and II,
and also the chaining variables of the independent part I and II.

3. Calculate list L_1 by independent message word I and indpendent part I.
Calculate list L_2 by independent message word II and independent part II.

4. Search for a collision of L_1 and L_2, the corresponding initial value and
message of this collision is a pseudo preimage.

////
随后又出现了带完全二分结构体[23]的中间相遇攻击等方法.带完全二分结构体的中间相
遇攻击如图3所示，其中 IW I， IW II表示独立消息字.
////


////
使用中间相遇攻击方法，Zou等人[24]在 ICISC 2011上给出了从第1步开始的
28步SM3密码杂凑算法的原像攻击和从中间开始的30步SM3密码杂凑算法的原像攻击.
2012年，Wang和Shen[25]使用差分中间相遇攻击方法给出了29步和30步SM3密码杂凑
算法的原像攻击，同时给出了31步和32步SM3密码杂凑算法的伪原像攻击.所有的分
析结果均从第1步开始.
////

By using meet-in-the-middle attack, Zou et al. presented a 1st step started
28-step preimage attack and a middle started 30-step preimage attack against
SM3 algorithm on ICISC 2011. In 2012, Wang and Shen used differential meet-
in-the-middle attack to present 29-step and 30-step preimage attack against
SM3 algorithm, as well as 31-step and 32-step pseudo preimage attack against
SM3 algorithm. All analysis results started from the frist step.

////
对SM3密码杂凑算法的区分攻击主要是使用飞去来器(boomerang)区分攻击，
其主要思想是使用中间一步或者多步链接变量的衔接将2条短的差分路线构造长的差
分路线，进而构造出满足输入输出差分的四元组.如图4所示，一般过程可以描述
如下:

1)选择合适的消息差分，构造攻击所需 的短差分路线.消息差分的选取应尽量是充
分条件出现在衔接位置附近.
2)检测衔接位置的充分条件是否矛盾.
3)随机选择衔接位置的链接变量，使用消息修改技术，使得被修改的消息满足尽可
能多的充分条件.
4)从衔接位置开始，向两端构造相应测差分路线，进而推导出对应的输入输出差分. 

在 SAC 2012 上，Kircanski 等人[26]给出了32步到35步SM3密码杂凑算法压缩函数的飞去来器区分攻击，
同时给出了32步和33步的区分攻击实例以及利用SM3密码杂凑算法的移位特点，
给出了SM3-XOR(将SM3密码杂凑算法中所有的非线性运算用异或运算代替)的滑动-移位特性. 

2014年，Bai等人[27]改进了SM3密码杂凑算法的飞去来器区分攻击，
给出了34步到37步飞去来器区分攻击以及34步和35步的区分攻击实例. 

SM3密码杂凑算法的分析结果如表4所示：

[table 4]
////

=== Distinguishing Attack

The distinguishing attack against SM3 algorithm is mainly the boomerang
distinguishing attack. The main idea of this attack is to use chaining
variables from one or multiple steps to form a long differential path by
conjuncting two short differential paths and then to construct the quartet
which fulfills the input and output differentials. The process is generally
described as the following steps:

1. Select proper message differential and construct the short differential
paths. The message differential should be selected that the sufficent conditions
appear around the conjuction position.

2. Test the sufficient conditions that are around the conjuction postion to see
if they are conflicted or not.

3. Randomly select chaining varibales at conjunction position and then apply
the message modification technology to let the modified message fulfill as
many sufficient conditions as possible.

4. Start from the conjuction position, construct corresponding differential
paths toward each side, to derive corresponding input and output differentials.

On SAC 2012, Kircanski et al. presented 32-step to 35-step boomerang
distinguishing attack against SM3 algorithm along with the instances of 32-step
and 33-step attack. They also utilized the shifting characteristic of SM3
algorithm to replace all non-linear opearations with XOR operations to get the
SM3-XOR characteristic. In 2014, Bai et al. improved the boomerang
distinguishing attack against SM3 algorihtm. They presented 34-step to 37-step
attack and the instances of 34-step and 35-step of that attack. The cryptanalysis
results of SM3 hash algorithm are shown in the following table:

////
== 4.2 SM3密码杂凑算法和其他杂凑标准对比结果
== Cryptanalysis comparision with other hash algorithms

//4.2 SM3密码杂凑算法和其他杂凑标准对比结果

SM3密码杂凑算法和其他杂凑标准SHA-1, SHA-2, RIPEMD-128, RIPEMD-160, 
Whirlpool, Stribog和KECCAK的安全性分析对比结果如表5所示：

[table 5]

从表5可以得出:在碰撞攻击方面，SM3密码杂凑算法的攻击百分比仅比KECCAK高，
比其他杂凑标准低，但在MI>SHA类算法中最低，仅占总步数的31%;
在原像攻击方面，SM3密码杂凑算法的攻击百分比仅比KECCAK高，
比其他杂凑标准低，但在MI>SHA类算法中最低，占总步数的47%;
在区分器攻击方面，SM3密码杂凑算法均比其他杂凑标准低，仅有58%，
约占总步数的一半左右.这些分析结果体现了SM3密码杂凑算法的高安全性.

////

== Comparision with Other Algorithms

The results of SM3 algorithm compares with other hash algorihtms as SHA-1,
SHA-2, RIPEMD-128, RIP-160, Whirlpool, Stribog and KECCAK are shown in the
following table:

According to the results, for collision attack, the attack percentage of SM3
algorithm is only higher than KECCAK, and it is lower that all other algorithms.
But among all MD-SHA-like algorithms, SM3 has the lowest percentage - 31% of
all steps; for preimage attack, the attack percentage of SM3 algorithm is only
higher than KECCAK, and it is lower that all other algorithms. But among all
MD-SHA-like alogrithms, SM3 has the lowest percentage - 47% of all steps; for
distinguish attack, the attack percentage of SM3 is the lowest, which is 58%,
about half of all steps. These results reflect the high security of SM3
algorithm.
