[#oid]
= Object Identifier

The Object Identifier for SM3 is identified through these OIDs.

== GM/T OIDs

=== SCA OID Prefix

All SM3 GM/T OIDs belong under the "1.2.156.10197" OID prefix,
registered by the Chinese Cryptography Standardization Technology
Committee ("CCSTC"), a committee under the SCA.  Its components are
described below in ASN.1 notation.

* "id-ccstc" `{iso(1) member-body(2) cn(156) ccstc(10197)}`

=== Hash Algorithms

These SM3 OIDs are assigned in <<GMT-0004-2012>> and described in
<<GBT.33560-2017>>.

"1.2.156.10197.1.400" for "Hash Algorithms":

* "id-hash" `{id-ccstc sm-scheme(1) hash(400)}`

"1.2.156.10197.1.401" for "Hash Algorithm: SM3 Algorithm":

* "id-hash-sm3" `{id-ccstc sm-scheme(1) sm3(401)}`

"1.2.156.10197.1.401.1" for "Hash Algorithm: SM3 Algorithm used
without secret key":

* "id-hash-sm3-nsk" `{id-hash-sm3 no-secret-key(1)}`

"1.2.156.10197.1.401.2" for "Hash Algorithm: SM3 Algorithm used with
secret key":

* "id-hash-sm3-sk" `{id-hash-sm3 secret-key(2)}`


=== Integrated Algorithms

These OIDs that involves SM3 are described in <<GBT.33560-2017>>.

"1.2.156.10197.1.500" for "Integrated Algorithms":

* "id-int" `{id-ccstc sm-scheme(1) integrated(500)}`

"1.2.156.10197.1.501"	for "Digital Signature: SM2 and SM3"

* "id-dsa-sm2sm3" `{id-int dsa-sm2sm3(501)}`

"1.2.156.10197.1.502"	for "Digital Signature: SM9 and SM3"

* "id-dsa-sm9sm3" `{id-int dsa-sm9sm3(502)}`

"1.2.156.10197.1.504"	for "Digital Signature: RSA and SM3"

* "id-dsa-rsasm3" `{id-int dsa-rsasm3(504)}`


=== Standard Identification

The "SM3 Hash Algorithm" standard is assigned the
"1.2.156.10197.6.1.1.4" OID in <<GMT-0004-2012>> and this assignment
is also described in <<GBT.33560-2017>>.

* "id-standard-sm3" `{id-ccstc standard(1) fundamental(1) algorithm(1) sm3(4)}`

Note that this OID is purely used for identifying the SM3 standard
itself.


== ISO OID

SM3 is assigned the OID "1.0.10118.3.0.65" ("id-dhf-SM3") in
<<ISO.IEC.10118-3>>. Its components are described below in ASN.1
notation.

* "is10118-3" `{iso(1) standard(0) hash-functions(10118) part3(3)}`

* "id-dhf" `{is10118-3 algorithm(0)}`

* "id-dhf-SM3" `{id-dhf sm3(65)}`

