
= References

[bibliography]
== Normative References

//bibliography::norm[]
++++

<reference anchor='GBT.32905-2016' target='www.gb688.cn/bzgk/gb/newGbInfo?hcno=45B1A67F20F3BF339211C391E9278F5E'>
<!--http://www.sac.gov.cn/SACSearch/search?channelid=97779&templet=gjcxjg_detail.jsp&searchword=STANDARD_CODE=%27GB/T%2032905-2016%27 -->
  <front>
    <title>GB/T 32905-2016: Information security techniques -- SM3 cryptographic hash algorithm</title>
    <author>
      <organization>Standardization Administration of the People's Republic of China</organization>
      <address>
        <postal>
         <street>No. 9 Madian Donglu, Haidian District</street>
         <city>Beijing</city>
         <region>Beijing</region>
         <code>100088</code>
         <country>People's Republic of China</country>
        </postal>
        <phone>+86 (0)10 8226-2609</phone>
        <!--<email>contact@oscca.gov.cn</email>-->
        <uri>http://www.sac.gov.cn</uri>
      </address>
    </author>
    <date day='29' month='August' year='2016'/>
  </front>
</reference>


<reference anchor='GMT-0004-2012' target='http://www.oscca.gov.cn/Column/Column_32.htm'>
  <front>
    <title>GM/T 0004-2012: SM3 Cryptographic Hash Algorithm</title>
    <author>
      <organization>Organization of State Commercial Administration of China</organization>
      <address>
        <postal>
         <street>7 Dian Chang Lu, Fengtai Qu</street>
         <city>Beijing</city>
         <region>Beijing</region>
         <code>100036</code>
         <country>People's Republic of China</country>
        </postal>
        <phone>+86 (0)10 5970-3789</phone>
        <!--<email>contact@oscca.gov.cn</email>-->
        <uri>http://www.oscca.gov.cn</uri>
      </address>
    </author>
    <date day='21' month='March' year='2012'/>
  </front>
</reference>

++++


[bibliography]
== Informative References

//bibliography::info[]
++++

<reference anchor='OSCCA' target='http://www.oscca.gov.cn'>
  <front>
    <title>Organization of State Commercial Administration of China</title>
    <author>
      <organization>Organization of State Commercial Administration of China</organization>
      <address>
        <postal>
         <street>7 Dian Chang Lu, Fengtai Qu</street>
         <city>Beijing</city>
         <region>Beijing</region>
         <code>100036</code>
         <country>People's Republic of China</country>
        </postal>
        <phone>+86 (0)10 5970-3789</phone>
        <!--<email>contact@oscca.gov.cn</email>-->
        <uri>http://www.oscca.gov.cn</uri>
      </address>
    </author>
    <date month='May' year='2017'/>
  </front>
</reference>


<reference anchor='NIST.FIPS.180-1' target='https://www.nist.gov/publications/secure-hash-standard-shs-2?pub_id=917977'>
  <front>
    <title>NIST Federal Information Processing Standard 180-1: Secure Hash Standard (SHS)</title>
    <author initials="E." surname="Barker" fullname="Elaine B. Barker">
      <organization>National Institute of Standards and Technology</organization>
      <address>
        <postal>
          <street>100 Bureau Drive</street>
          <city>Gaithersburg</city>
          <region>MD</region>
          <code>20899-8930</code>
          <country>United States</country>
        </postal>
        <uri>http://www.nist.gov/</uri>
      </address>
    </author>
    <date day='17' month='April' year='1995'/>
  </front>
</reference>


<reference anchor='NIST.FIPS.180-2' target='https://csrc.nist.gov/csrc/media/publications/fips/180/2/archive/2002-08-01/documents/fips180-2.pdf'>
  <front>
    <title>NIST Federal Information Processing Standard 180-2: Secure Hash Standard (SHS)</title>
    <author initials="E." surname="Barker" fullname="Elaine B. Barker">
      <organization>National Institute of Standards and Technology</organization>
      <address>
        <postal>
          <street>100 Bureau Drive</street>
          <city>Gaithersburg</city>
          <region>MD</region>
          <code>20899-8930</code>
          <country>United States</country>
        </postal>
        <uri>http://www.nist.gov/</uri>
      </address>
    </author>
    <date day='1' month='August' year='2002'/>
  </front>
</reference>

<reference anchor='NIST.FIPS.202' target='https://doi.org/10.6028/NIST.FIPS.202'>
  <front>
    <title>NIST Federal Information Processing Standard 202: SHA-3 Standard: Permutation-Based Hash and Extendable-Output Functions</title>
    <author>
      <organization>National Institute of Standards and Technology</organization>
      <address>
        <postal>
          <street>100 Bureau Drive</street>
          <city>Gaithersburg</city>
          <region>MD</region>
          <code>20899-8930</code>
          <country>United States</country>
        </postal>
        <uri>http://www.nist.gov/</uri>
      </address>
    </author>
    <date day='5' month='August' year='2015'/>
  </front>
</reference>


<reference anchor='WXY' target='http://www.tsinghua.edu.cn/publish/casen/1695/2010/20101224093253705266640/20101224093253705266640_.html'>
 <!-- 新华书目报　2010年11月25日 孙梦姝 -->
  <front>
    <title>Xiaoyun Wang -- Institute of Advanced Study -- Tsinghua University</title>
    <author initials="X." surname="Wang" fullname="Xiaoyun Wang">
      <organization>Institute for Advanced Study, Tsinghua University</organization>
      <address>
        <postal>
          <street></street>
          <city>Beijing</city>
          <code>100084</code>
          <country>People's Republic of China</country>
        </postal>
        <email>xiaoyunwang@mail.tsinghua.edu.cn</email>
      </address>
    </author>
    <date day='31' month='October' year='2017'/>
  </front>
</reference>

<reference anchor='SM3-Details' target=''>
  <front>
    <title>SM3 Cryptographic Hash Algorithm</title>
    <author initials="X." surname="Wang" fullname="Xiaoyun Wang">
      <organization>Institute for Advanced Study, Tsinghua University</organization>
      <address>
        <postal>
          <street></street>
          <city>Beijing</city>
          <code>100084</code>
          <country>People's Republic of China</country>
        </postal>
        <email>xiaoyunwang@mail.tsinghua.edu.cn</email>
      </address>
    </author>
    <author initials="H." surname="Yu" fullname="Hongbo Yu">
      <organization>Department of Computer Science and Technology, Tsinghua University</organization>
      <address>
        <postal>
          <street></street>
          <city>Beijing</city>
          <code>100084</code>
          <country>People's Republic of China</country>
        </postal>
      </address>
    </author>
    <date day='25' month='October' year='2016'/>
  </front>
</reference>


<reference anchor='SM3-Boomerang' target='https://doi.org/10.1049/iet-ifs.2013.0380'>
  <front>
    <title>Improved Boomerang Attacks on Round-Reduced SM3 and Keyed Permutation of BLAKE-256</title>
      <!--IET Information Security ( Volume: 9, Issue: 3, 5 2015 )-->
    <author initials="D." surname="Bai" fullname="Dongxia Bai">
      <organization>Department of Computer Science and Technology, Tsinghua University</organization>
      <address>
        <postal>
          <street>Tsinghua University</street>
          <city>Beijing</city>
          <code>100084</code>
          <country>People's Republic of China</country>
        </postal>
        <email>baidx10@mails.tsinghua.edu.cn</email>
        <uri>http://www.tsinghua.edu.cn</uri>
      </address>
    </author>
    <author initials="H." surname="Yu" fullname="Hongbo Yu">
      <address>
        <postal>
          <street>Tsinghua University</street>
          <city>Beijing</city>
          <code>100084</code>
          <country>People's Republic of China</country>
        </postal>
        <email>yuhongbo@mail.tsinghua.edu.cn</email>
        <uri>http://www.tsinghua.edu.cn</uri>
      </address>
    </author>
    <author initials="G." surname="Wang" fullname="Gaoli Wang">
      <organization>School of Computer Science and Technology, Donghua University</organization>
      <address>
        <postal>
         <street>Donghua University</street>
         <city>Shanghai</city>
         <!--<region>CA</region>-->
         <code>201620</code>
         <country>People's Republic of China</country>
        </postal>
        <email>wanggaoli@dhu.edu.cn</email>
        <uri>https://www.dhu.edu.cn</uri>
      </address>
    </author>
    <author initials="X." surname="Wang" fullname="Xiaoyun Wang">
      <organization>Institute for Advanced Study, Tsinghua University</organization>
      <address>
        <postal>
          <street>Tsinghua University</street>
          <city>Beijing</city>
          <code>100084</code>
          <country>People's Republic of China</country>
        </postal>
        <email>xiaoyunwang@mail.tsinghua.edu.cn</email>
        <uri>http://www.tsinghua.edu.cn</uri>
      </address>
    </author>
    <date day='16' month='April' year='2015'/>
  </front>
</reference>

<reference anchor='BOTAN' target='https://botan.randombit.net'>
  <front>
    <title>Botan: Crypto and TLS for C++11</title>
    <author initials="J. E." surname="Lloyd" fullname="Jack E. Lloyd">
      <organization>Botan Project</organization>
      <address>
        <postal>
          <street></street>
          <country>United States of America</country>
        </postal>
        <email>jack@randombit.net</email>
        <uri>https://botan.randombit.net</uri>
      </address>
    </author>
    <date day='31' month='October' year='2017'/>
  </front>
</reference>

<reference anchor='OPENSSL' target='https://www.openssl.org'>
  <front>
    <title>OpenSSL: Cryptography and SSL/TLS Toolkit</title>
    <author>
      <organization>OpenSSL Software Foundation</organization>
      <address>
        <postal>
          <street>20-22 Wenlock Road</street>
          <city>London</city>
          <code>N1 7GU</code>
          <country>United Kingdom</country>
        </postal>
        <phone>+44 17 8550 8015</phone>
        <email>info@opensslfoundation.org</email>
        <uri>https://www.openssl.org</uri>
      </address>
    </author>
    <date day='31' month='October' year='2017'/>
  </front>
</reference>

<reference anchor='ISO.IEC.10118-3' target='https://www.iso.org/standard/67116.html'>
  <front>
    <title>ISO/IEC FDIS 10118-3 -- Information technology -- Security techniques -- Hash-functions -- Part 3: Dedicated hash-functions</title>
    <author>
      <organization>International Organization for Standardization</organization>
      <address>
        <postal>
          <street>BIBC II</street>
          <street>Chemin de Blandonnet 8</street>
          <street>CP 401</street>
          <city>Vernier</city>
          <region>Geneva</region>
          <code>1214</code>
          <country>Switzerland</country>
        </postal>
        <phone>+41 22 749 01 11</phone>
        <email>central@iso.org</email>
        <uri>https://www.iso.org/</uri>
      </address>
    </author>
    <date day='15' month='September' year='2017'/>
  </front>
</reference>

<reference anchor='NIST.FIPS.180-4' target='http://dx.doi.org/10.6028/NIST.FIPS.180-4'>
  <front>
    <title>FIPS 180-4 Secure Hash Standard (SHS)</title>
    <author>
      <organization>National Institute of Standards and Technology</organization>
      <address>
        <postal>
          <street>100 Bureau Drive</street>
          <city>Gaithersburg</city>
          <region>MD</region>
          <code>20899-8900</code>
          <country>United States</country>
        </postal>
        <uri>http://www.nist.gov/</uri>
      </address>
    </author>
    <date month='August' year='2015'/>
  </front>
</reference>

<reference anchor='SM3' target='http://www.oscca.gov.cn/UpFile/20101222141857786.pdf'>
<!-- <reference anchor='SM3' target='http://info.dacas.cn/sharedimages/ARTICLES/SMAlgorithms/SM3.pdf'> -->
  <front>
    <title>SM3 Cryptographic Hash Algorithm</title>
    <author>
      <organization>Organization of State Commercial Administration of China</organization>
      <address>
        <postal>
         <street>7 Dian Chang Lu, Fengtai Qu</street>
         <city>Beijing</city>
         <region>Beijing</region>
         <code>100036</code>
         <country>People's Republic of China</country>
        </postal>
        <phone>+86 (0)10 5970-3789</phone>
        <!--<email>contact@oscca.gov.cn</email>-->
        <uri>http://www.oscca.gov.cn</uri>
      </address>
    </author>
    <date month='December' year='2010'/>
  </front>
</reference>

include::../reference.RFC.2119.xml[lines=3..-1]
include::../reference.RFC.6150.xml[lines=3..-1]
include::../reference.RFC.6234.xml[lines=3..-1]

++++

